In [1]:
import pathlib
import pandas as pd

from log_parser import parse_game_log


BASE_DIR = pathlib.Path().resolve().parent

display(BASE_DIR)

WindowsPath('C:/Users/SSAFY/git/ssamantle-deploy')

In [2]:
game_1 = parse_game_log(
    log_file=BASE_DIR / 'volume/server/logs' / 'app.log',
    start_time=pd.to_datetime("2026-04-27 08:25:33.703"),
    end_time=pd.to_datetime("2026-04-27 08:39:51.318"),
)

display(game_1.game)

,hostname,host_session_id,target_word,status,started_at,ended_at,created_at
0,string,a323e7db-8ae8-4150-a6e0-b9b99d7906ec,봄바람,PREGAME,2026-04-27 08:25:33.703,2026-04-27 08:39:51.318,2026-04-27 08:25:33.703

In [3]:
game_2 = parse_game_log(
    log_file=BASE_DIR / 'volume/server/logs' / 'app.log',
    start_time=pd.to_datetime("2026-04-27 08:39:51.319"),
    end_time=pd.to_datetime("2026-04-27 08:59:59.999"),
)

display(game_2.game)

,hostname,host_session_id,target_word,status,started_at,ended_at,created_at
0,string,606d3d7c-948a-4f59-85c7-5472763ceb59,박하사탕,PREGAME,2026-04-27 08:39:51.319,2026-04-27 08:59:59.999,2026-04-27 08:39:51.319

In [4]:
game_1.game.to_csv(BASE_DIR / 'game_1.csv', index=False)
game_1.participant.to_csv(BASE_DIR / 'participant_1.csv', index=False)
game_1.guess_history.to_csv(BASE_DIR / 'guess_history_1.csv', index=False)

game_2.game.to_csv(BASE_DIR / 'game_2.csv', index=False)
game_2.participant.to_csv(BASE_DIR / 'participant_2.csv', index=False)
game_2.guess_history.to_csv(BASE_DIR / 'guess_history_2.csv', index=False)